import React, { useState } from 'react';

export default function LegalPage() {
  const [activeTab, setActiveTab] = useState('privacy');

  return (
    <div className="legal-view-container" style={{ paddingTop: '100px', minHeight: '80vh' }}>
      <section className="mile mile--tight">
        <span className="milemark">Legal · Disclosures</span>
        <div className="wrap" style={{ maxWidth: '800px' }}>
          <div className="mile-head" style={{ marginBottom: '32px' }}>
            <p className="eyebrow">Attribution &amp; Rules</p>
            <h2>Legal Framework &amp; Compliance Docs</h2>
          </div>

          {/* Navigation Tabs */}
          <div style={{ display: 'flex', borderBottom: '2px solid var(--line)', gap: '24px', marginBottom: '28px' }}>
            {['privacy', 'terms', 'attribution'].map(tab => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                style={{
                  background: 'none',
                  border: 'none',
                  borderBottom: activeTab === tab ? '3px solid var(--green)' : '3px solid transparent',
                  padding: '8px 12px 12px 12px',
                  fontWeight: 'bold',
                  fontSize: '1rem',
                  color: activeTab === tab ? 'var(--green-950)' : 'var(--muted)',
                  cursor: 'pointer',
                  textTransform: 'capitalize'
                }}
              >
                {tab === 'attribution' ? 'Data Attribution (ODbL)' : tab + ' policy'}
              </button>
            ))}
          </div>

          <div className="panel" style={{ padding: '32px', minHeight: '300px', alignContent: 'start', lineHeight: '1.7', color: 'var(--ink)' }}>
            {activeTab === 'privacy' && (
              <div>
                <h3 style={{ marginBottom: '16px', color: 'var(--green-950)' }}>Privacy Policy</h3>
                <p style={{ marginBottom: '12px' }}>
                  At Trip Planner EV, we value your trust. We do not sell your location coordinates or travel histories to third-party brokers.
                </p>
                <h4 style={{ margin: '16px 0 8px 0', color: 'var(--green-900)' }}>1. Data Collection</h4>
                <p style={{ marginBottom: '12px', fontSize: '.95rem', color: 'var(--muted)' }}>
                  We collect account emails, connected vehicle specifications (battery size, consumption characteristics), and check-in logs. Location services are only queried with explicit browser consent to identify nearby chargers.
                </p>
                <h4 style={{ margin: '16px 0 8px 0', color: 'var(--green-900)' }}>2. Cookies &amp; Tracking</h4>
                <p style={{ fontSize: '.95rem', color: 'var(--muted)' }}>
                  We use browser localStorage to cache your plans and credentials locally. Our website uses privacy-friendly analytics trackers (Plausible) which operate without tracking cookies or compiling cross-site profiles.
                </p>
              </div>
            )}

            {activeTab === 'terms' && (
              <div>
                <h3 style={{ marginBottom: '16px', color: 'var(--green-950)' }}>Terms of Service</h3>
                <p style={{ marginBottom: '12px' }}>
                  By accessing Trip Planner EV, you agree to comply with the rules of this platform.
                </p>
                <h4 style={{ margin: '16px 0 8px 0', color: 'var(--green-900)' }}>1. Disclaimers</h4>
                <p style={{ marginBottom: '12px', fontSize: '.95rem', color: 'var(--muted)' }}>
                  All range calculations, tariff estimates, and charger reliability scores are estimates generated by physics-based algorithms and crowdsourced logs. Real-world range depends on battery age, speed, terrain, and weather variables. Do not rely solely on this app for critical navigation.
                </p>
                <h4 style={{ margin: '16px 0 8px 0', color: 'var(--green-900)' }}>2. Permissible Use</h4>
                <p style={{ fontSize: '.95rem', color: 'var(--muted)' }}>
                  Scraping our calculated grades or bulk downloading raw outputs is prohibited. B2B systems must license our datasets via the official API portal.
                </p>
              </div>
            )}

            {activeTab === 'attribution' && (
              <div>
                <h3 style={{ marginBottom: '16px', color: 'var(--green-950)' }}>Data Sources &amp; Attribution</h3>
                <p style={{ marginBottom: '16px' }}>
                  Our calculation models rely on open crowdsourced networks. We credit and attribute the following databases:
                </p>
                
                <div style={{ background: 'var(--paper)', padding: '20px', borderRadius: '8px', border: '1px solid var(--line)', marginBottom: '20px' }}>
                  <h4 style={{ color: 'var(--green-900)', margin: '0 0 6px 0' }}>OpenChargeMap API</h4>
                  <p style={{ fontSize: '.9rem', color: 'var(--muted)' }}>
                    Core charger station configurations and port specs are sourced from the OpenChargeMap database. License: Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0).
                  </p>
                </div>

                <div style={{ background: 'var(--paper)', padding: '20px', borderRadius: '8px', border: '1px solid var(--line)' }}>
                  <h4 style={{ color: 'var(--green-900)', margin: '0 0 6px 0' }}>OpenStreetMap Contributors</h4>
                  <p style={{ fontSize: '.9rem', color: 'var(--muted)' }}>
                    Geocoding, highway vectors, and amenity coordinates are derived from OpenStreetMap database extracts. License: Open Database License (ODbL).
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>
      </section>
    </div>
  );
}
